#!/usr/bin/env node
// Generates design/.ds-entry.jsx for the design-sync converter (cfg.buildCmd).
// The kit files are browser scripts sharing ONE global lexical scope (loaded
// as <script type="text/babel"> by design/ui_kits/macos_app/index.html), not
// modules. Concatenating them in the page's own load order inside one module
// scope preserves those semantics exactly. Three deterministic transforms:
//   1. strip the script-tag export lines (`window.X = X;`) — real ES exports
//      replace them, so the bundle never clobbers browser globals like
//      window.Notification;
//   2. rewrite kit-page-relative asset path strings ("../../assets/…") to
//      imported identifiers — esbuild's dataurl loader inlines the SVGs so
//      app glyphs render inside claude.ai/design, where the kit page's
//      relative paths do not exist;
//   3. append `export { … }` for every component named in
//      .design-sync/config.json componentSrcMap (non-null entries).
// Output is a pure function of the kit sources + config: same inputs, same
// bytes. Never edit or commit design/.ds-entry.jsx (gitignored).

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const kitDir = join(repo, 'design', 'ui_kits', 'macos_app');
const cfg = JSON.parse(readFileSync(join(repo, '.design-sync', 'config.json'), 'utf8'));

const indexHtml = readFileSync(join(kitDir, 'index.html'), 'utf8');
const files = [...indexHtml.matchAll(/<script type="text\/babel" src="([^"]+\.jsx)"/g)].map((m) => m[1]);
if (!files.length) throw new Error('no <script type="text/babel" src="*.jsx"> tags in kit index.html');

const assetImports = new Map(); // path under design/ -> identifier
let body = '';
for (const f of files) {
  let src = readFileSync(join(kitDir, f), 'utf8');
  src = src.replace(/^window\.[A-Za-z_$][\w$]* *= *[A-Za-z_$][\w$]*;? *$/gm, '');
  src = src.replace(/^Object\.assign\(window,[\s\S]*?\);\s*$/m, '');
  src = src.replace(/"\.\.\/\.\.\/(assets\/[^"]+)"/g, (_, rel) => {
    if (!assetImports.has(rel)) assetImports.set(rel, `__mpAsset${assetImports.size}`);
    return assetImports.get(rel);
  });
  body += `// ============ ${f} ============\n${src}\n`;
}

const names = Object.entries(cfg.componentSrcMap ?? {})
  .filter(([, v]) => v !== null)
  .map(([k]) => k)
  .sort();
if (!names.length) throw new Error('componentSrcMap in .design-sync/config.json is empty — nothing to export');
const missing = names.filter((n) => !new RegExp(`\\bconst ${n} *=`).test(body));
if (missing.length) throw new Error(`componentSrcMap names not found as top-level consts in the kit: ${missing.join(', ')}`);

const header = [
  '// GENERATED by .design-sync/make-entry.mjs — do not edit, do not commit.',
  "import React from 'react';",
  ...[...assetImports].map(([rel, id]) => `import ${id} from './${rel}';`),
].join('\n');

writeFileSync(join(repo, 'design', '.ds-entry.jsx'), `${header}\n\n${body}\nexport { ${names.join(', ')} };\n`);
console.log(`.ds-entry.jsx: ${files.length} kit files, ${names.length} exports, ${assetImports.size} inlined assets`);
