"""`mp backup <dir>`: archive the state that cannot be recreated (STOR2).

meeting-pipe accumulates an irreplaceable corpus across four roots, and until now
had no backup story at all. What goes in:

- the library (`recording.output_dir`): recordings and every sidecar
- `digests/`, the generated weekly reviews
- `~/.config/meeting-pipe/`: config, workflows, voiceprint, roster, glossary
- the corrections corpus in `~/Library/Application Support/MeetingPipe/corrections/`

What deliberately stays out:

- **`originals/`**, the kept pre-redaction recordings. ADR 0016 makes them mode
  0600 and excludes them from Time Machine precisely because they are the most
  sensitive thing on disk. Writing them into a tarball the owner copies to a NAS
  would defeat the property that ADR establishes. The redacted recording in the
  library is the canonical artifact, and it is backed up.
- **`secrets.env`**, the legacy plaintext file SEC8 migrated into the Keychain.
- **Keychain values.** The manifest names the three items to re-create; the secrets
  themselves are never exported. `mp restore` prints the commands.
- **`published/`** (republish regenerates it) and the caches (waveform peaks,
  HuggingFace models), which rebuild on demand.

Stdlib `tarfile`, no new dependency. Compression is `gzip` at level 1 on purpose:
JSON sidecars compress well even at level 1, and WAV barely compresses at any
level, so the default level 6 would burn minutes of CPU on a multi-gigabyte
library for almost nothing.
"""
from __future__ import annotations

import argparse
import io
import json
import tarfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from . import entry, storage
from .config import KEYCHAIN_SERVICE, MANAGED_SECRET_KEYS, Config

MANIFEST_NAME = "manifest.json"
MANIFEST_SCHEMA_VERSION = 1

#: Never archived, whatever root it is found under. `secrets.env` is the legacy
#: plaintext file; `.last-backup.json` is a fact about *this* Mac, and restoring a
#: stale one would make doctor report a backup that never happened here.
EXCLUDED_NAMES = {"secrets.env", ".last-backup.json"}

#: `config.toml` names this machine's library path, so a restore must not clobber
#: the one the user just wrote on the new Mac. Everything else under `config/`
#: (workflows, roster, voiceprint, glossary) is machine-independent and restores.
CONFIG_PRESERVED = "config.toml"

#: Recording extensions, skipped under `--no-audio`. Mirrors Swift's
#: `MeetingStore.finalRecordingExtensions`.
AUDIO_SUFFIXES = {".wav", ".flac"}

EXCLUSIONS = [
    {
        "path": "originals/",
        "reason": "sensitive pre-redaction recordings; ADR 0016 excludes them from backups",
    },
    {"path": "secrets.env", "reason": "legacy plaintext secrets; superseded by the Keychain"},
    {"path": "published/", "reason": "regenerated by republish"},
    {"path": "caches", "reason": "waveform peaks and downloaded models rebuild on demand"},
]


@dataclass(frozen=True)
class Root:
    """One source directory and the prefix it takes inside the archive."""

    name: str
    prefix: str
    source: Path
    #: Only the library holds recordings, so only it honours `--no-audio`.
    holds_audio: bool = False


def backup_roots(cfg: Config, home: Path | None = None) -> list[Root]:
    library = cfg.recording.output_dir
    return [
        Root("library", "library", library, holds_audio=True),
        Root("digests", "digests", storage.digests_dir(library)),
        Root("config", "config", storage.config_dir(home)),
        Root("corrections", "corrections", storage.corrections_dir(home)),
    ]


def _should_include(path: Path, *, holds_audio: bool, include_audio: bool) -> bool:
    if path.name in EXCLUDED_NAMES:
        return False
    if holds_audio and not include_audio and path.suffix.lower() in AUDIO_SUFFIXES:
        return False
    return True


def _add_root(tar: tarfile.TarFile, root: Root, *, include_audio: bool) -> dict[str, object]:
    """Archive one root, returning its manifest entry. A root that does not exist
    contributes an entry with zero files rather than being silently dropped, so a
    restore can tell "you had no digests" from "the backup forgot digests"."""
    files = 0
    total = 0
    if root.source.is_dir():
        for path in sorted(root.source.rglob("*")):
            if path.is_symlink() or not path.is_file():
                continue
            if not _should_include(path, holds_audio=root.holds_audio, include_audio=include_audio):
                continue
            arcname = f"{root.prefix}/{path.relative_to(root.source)}"
            tar.add(path, arcname=arcname, recursive=False)
            files += 1
            total += path.stat().st_size
    return {
        "name": root.name,
        "archive_prefix": root.prefix,
        "source": str(root.source),
        "files": files,
        "bytes": total,
    }


def build_manifest(
    root_entries: list[dict[str, object]], *, include_audio: bool, created_at: str
) -> dict[str, object]:
    from . import __version__

    return {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "created_at": created_at,
        "tool_version": __version__,
        "audio_included": include_audio,
        "roots": root_entries,
        "keychain": {
            "service": KEYCHAIN_SERVICE,
            "accounts": list(MANAGED_SECRET_KEYS),
            "note": (
                "Secret values are never exported. Re-create each item on the new Mac with: "
                f"security add-generic-password -U -s {KEYCHAIN_SERVICE} -a <ACCOUNT> -w <VALUE>"
            ),
        },
        "excluded": EXCLUSIONS,
    }


def create_backup(
    cfg: Config,
    destination: Path,
    *,
    include_audio: bool = True,
    home: Path | None = None,
    now: datetime | None = None,
) -> Path:
    """Write a dated archive into `destination` and stamp the backup marker."""
    now = now or datetime.now(timezone.utc)
    destination = destination.expanduser()
    destination.mkdir(parents=True, exist_ok=True)
    archive = destination / f"meeting-pipe-backup-{now.strftime('%Y%m%d-%H%M%S')}.tar.gz"

    entries: list[dict[str, object]] = []
    # compresslevel=1: see the module docstring.
    with tarfile.open(archive, "w:gz", compresslevel=1) as tar:
        for root in backup_roots(cfg, home):
            entries.append(_add_root(tar, root, include_audio=include_audio))

        manifest = build_manifest(
            entries, include_audio=include_audio, created_at=now.isoformat()
        )
        payload = json.dumps(manifest, indent=2).encode("utf-8")
        info = tarfile.TarInfo(MANIFEST_NAME)
        info.size = len(payload)
        info.mtime = int(now.timestamp())
        tar.addfile(info, io.BytesIO(payload))

    marker = storage.backup_marker(home)
    marker.parent.mkdir(parents=True, exist_ok=True)
    marker.write_text(
        json.dumps({
            "at": now.isoformat(),
            "archive": str(archive),
            "bytes": archive.stat().st_size,
            "audio_included": include_audio,
        }, indent=2),
        encoding="utf-8",
    )
    return archive


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="mp backup",
        description="Archive the meeting library, config, workflows, roster, and corrections.",
    )
    parser.add_argument("directory", type=Path, help="Where to write the dated archive.")
    parser.add_argument(
        "--no-audio",
        action="store_true",
        help="Skip recordings (.wav/.flac). Much smaller, but the restored Library "
             "shows meetings with no audio.",
    )
    args = parser.parse_args(argv)

    # SEC13: local-only work, but the entry contract is the entry contract.
    # `secrets=False`: a backup names the Keychain items, it never reads them.
    cfg = entry.prepare(secrets=False)

    include_audio = not args.no_audio
    archive = create_backup(cfg, args.directory, include_audio=include_audio)

    with tarfile.open(archive, "r:gz") as tar:
        member = tar.extractfile(MANIFEST_NAME)
        if member is None:  # pragma: no cover - create_backup always writes it
            raise RuntimeError(f"backup archive {archive} carries no {MANIFEST_NAME}")
        manifest = json.loads(member.read())

    print(f"wrote {archive}  ({storage.human_bytes(archive.stat().st_size)})")
    for root in manifest["roots"]:
        print(f"  {root['name']:12} {root['files']:>6} files  {storage.human_bytes(root['bytes'])}")
    if not include_audio:
        print("  recordings were skipped (--no-audio)")
    print()
    print("Keychain items are named in the manifest but never exported. Re-create them by hand:")
    for account in manifest["keychain"]["accounts"]:
        print(f"  security add-generic-password -U -s {manifest['keychain']['service']} -a {account} -w '<value>'")
    return 0
